spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/t_mo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: hkokim0309

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

cloud:
  aws:
    s3:
      bucket: tmo-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: AKIARDNJ65435CIIKE6G
      secret-key: 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

auth:
  jwt:
    secret: 7JWE66y06rKD64+E7ZWY6riw7Iur64uk7KCV66eQ7KeE7Ius6rCc7Iur7Ja0
    access-exp: 86400




