spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/t_mo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: hkokim0309

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

cloud:
  aws:
    s3:
=======
      bucket: ${BUCKET}
    region:
      static: ${STATIC}
    stack:
      auto: false
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
      
auth:
  jwt:
    secret: ${SECRET}
    access-exp: ${ACCESS_EXP}
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}

auth:
  jwt:
    secret: ${SECRET}
    access-exp: ${ACCESS_EXP}



